server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_db
    username: postgres
    password: azamat
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql

  liquibase:
    change-log: classpath:master-changelog.yaml
    enabled: true

jwt:
  secret: effectiveMobile


logging:
  level:
    root: info
    org.springframework.web: debug

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

